version: '3.8'
services:
  api:
    build:
      context: ./api
    env_file:
      - ./api/.env
    ports:
      - "3000:3000"
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - api
    restart: unless-stopped
